/**
 * Vault-MOC renderer for `rea dash --emit-moc` (spec §4, third output mode).
 *
 * ## What this is
 *
 * A pure function `DashJson -> string` that renders the SAME aggregated
 * dashboard model the terminal and `--json` modes consume, as an Obsidian
 * map-of-content (MOC) markdown document. It is ONLY a renderer — it forks no
 * second data model, performs no discovery, reads no task artifact. The caller
 * (`runDash`) builds the model (which is where reconcile-on-read and the
 * per-project visibility rule already live) and hands it here.
 *
 * ## Why the model is the redaction boundary (spec §6)
 *
 * Sensitive-project visibility is enforced in `buildJson` BEFORE this renderer
 * runs: a `dashboard_visible: false` project never contributes task titles to
 * `DashJson` — it appears only in `hidden[]` as an opaque `{ item_count }`
 * count. Because this renderer emits strictly from the model, a file written to
 * a shared vault carries exactly what the terminal view would show and never
 * more. A vault file is a higher disclosure surface than an ephemeral terminal,
 * so this renderer adds NO code path that re-reads titles for hidden projects.
 *
 * ## Determinism (spec §4 "overwrite-in-place", diff-friendly)
 *
 * Output is a pure function of the passed model: sections in fixed order,
 * items in the model's already-sorted order, no ambient clock or env read.
 * Rendering the same model twice is byte-identical, so re-emitting over an
 * existing vault file produces a minimal diff.
 */

import type {
  DashHealthFlag,
  DashHiddenSummary,
  DashItem,
  DashJson,
  DashProjectSummary,
} from './dash.js';

/**
 * Neutralize markdown / Obsidian control sequences in a disk-sourced field so a
 * task subject cannot inject a wikilink, embed, or code fence into the vault
 * document. Control codes are already stripped upstream by `clean()`; this is
 * the vault-specific layer (the terminal does not interpret `[[ ]]`).
 *
 * - `[[ ... ]]` / `![[ ... ]]` wikilinks + embeds → bracket run broken up
 * - backticks → escaped so a subject cannot open/close a code span
 * - pipes → escaped (defends any future table rendering)
 * - leading list/heading markers are inert here (subjects are rendered inline).
 */
export function mdInline(value: string): string {
  return value
    .replace(/`/g, '\\`')
    .replace(/\|/g, '\\|')
    .replace(/\[\[/g, '[ [')
    .replace(/\]\]/g, '] ]');
}

function itemLine(i: DashItem): string {
  return `- **[${mdInline(i.project)}]** \`${mdInline(i.task_id)}\` — ${mdInline(i.subject)}`;
}

function healthLine(h: DashHealthFlag): string {
  return `- **[${mdInline(h.project)}]** ${mdInline(h.detail)}`;
}

function hiddenLine(h: DashHiddenSummary): string {
  const plural = h.item_count === 1 ? '' : 's';
  return `- **[${mdInline(h.project)}]** ${h.item_count} item${plural}, hidden`;
}

function projectLine(p: DashProjectSummary): string {
  return `- **[${mdInline(p.project)}]** \`${mdInline(p.project_path)}\``;
}

function section<T>(heading: string, rows: T[], toLine: (row: T) => string): string[] {
  if (rows.length === 0) return [];
  return [`## ${heading}`, '', ...rows.map(toLine), ''];
}

/**
 * Render the aggregated dashboard model as a vault-ready MOC markdown document.
 * Pure and deterministic — no I/O, no clock, no env. `generated_at` is taken
 * from the model (the caller stamps it once), so a single build renders
 * identically every time.
 */
export function renderMoc(dash: DashJson): string {
  const g = dash.groups;
  const lines: string[] = [];

  // YAML frontmatter — marks the file as generated so it is not hand-edited,
  // and gives Obsidian a stable tag to query the morning view by.
  lines.push('---');
  lines.push('generated_by: rea dash');
  lines.push('do_not_edit: true');
  lines.push(`generated_at: ${dash.generated_at}`);
  lines.push(`mode: ${dash.mode}`);
  lines.push('tags:');
  lines.push('  - rea/dashboard');
  lines.push('  - rea/morning-view');
  lines.push('---');
  lines.push('');
  lines.push('# Morning View');
  lines.push('');
  lines.push(
    '> Generated by `rea dash --emit-moc`. Do not hand-edit — this file is ' +
      'overwritten in place on every emit.',
  );
  lines.push('');

  const attentionCount =
    g.awaiting.length +
    g.review_queue.length +
    g.in_flight.length +
    g.ready.length +
    g.health_flags.length +
    dash.hidden.length +
    dash.missing.length +
    dash.deregistered.length;

  if (attentionCount === 0) {
    const idle = g.idle.length;
    if (idle === 0) {
      lines.push('No rea projects registered yet.');
    } else {
      lines.push(`All clear — ${idle} project${idle === 1 ? '' : 's'} idle.`);
    }
    lines.push('');
  }

  lines.push(...section('Awaiting ratification / parked blockers', g.awaiting, itemLine));
  lines.push(...section('Review queue', g.review_queue, itemLine));
  lines.push(...section('In flight', g.in_flight, itemLine));
  lines.push(...section('Ready to start', g.ready, itemLine));
  lines.push(...section('Hidden projects', dash.hidden, hiddenLine));
  lines.push(...section('Health flags', g.health_flags, healthLine));
  lines.push(...section('Deregistered', dash.deregistered, projectLine));
  lines.push(...section('Missing', dash.missing, projectLine));
  lines.push(...section('Idle / healthy', g.idle, projectLine));

  // Collapse any trailing blank lines to a single terminating newline so the
  // output is a stable, diff-friendly block regardless of which sections fired.
  while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
  return lines.join('\n') + '\n';
}
