/**
 * 0.45.0 charter item 1 — hook hot-path profiling regression test.
 *
 * Imports the profiling harness directly and runs a small subset of
 * each shim (3 iterations + 1 warmup) so the test stays under the
 * vitest 30s timeout. The full baseline (10 iterations + 2 warmup)
 * is generated by `pnpm perf:hooks` and lives in
 * `docs/hook-perf-baseline.json`.
 *
 * # What this test guards
 *
 *   - The harness loads + runs without throwing
 *   - Every shipped shim produces a measurable result (no hangs, no
 *     timeouts at the harness's 30s spawnSync ceiling)
 *   - No shim's p95 exceeds the per-shim ceiling (currently 2000ms,
 *     loose to absorb CI noise but tight enough to catch absolute
 *     regressions like a new shim path that spawns extra Node procs)
 *   - The output sort is stable (p95 descending)
 *
 * # Why permissive
 *
 * Shim latency is sensitive to system load. CI shared runners can
 * spike ~3-5x above local times. The ceiling is loose so the test
 * doesn't flake on a busy runner, but tight enough that adding
 * another Node-spawn to the hot path (~150ms per spawn) shows up.
 *
 * Tighten as the baseline stabilizes across releases.
 */

import { describe, expect, it } from 'vitest';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readdirSync, statSync } from 'node:fs';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore - .mjs script with no .d.ts, dynamic import for vitest
import {
  runProfile,
  listShims,
  payloadForHook,
  payloadVariantsForHook,
  ceilingForShim,
} from '../../scripts/profile-hooks.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const HOOKS_DIR = path.join(REPO_ROOT, 'hooks');

describe('0.45.0 charter item 1 — profile-hooks harness', () => {
  it('listShims returns every .sh in hooks/ excluding _lib', () => {
    const shims = listShims() as string[];
    // Expect every entry to end in .sh and live in hooks/ root.
    for (const name of shims) {
      expect(name.endsWith('.sh')).toBe(true);
      const stat = statSync(path.join(HOOKS_DIR, name));
      expect(stat.isFile()).toBe(true);
    }
    // Cross-check against the filesystem directly.
    const fsList = readdirSync(HOOKS_DIR)
      .filter((f) => f.endsWith('.sh'))
      .filter((f) => {
        try {
          return statSync(path.join(HOOKS_DIR, f)).isFile();
        } catch {
          return false;
        }
      })
      .sort();
    expect(shims).toEqual(fsList);
  });

  it('payloadForHook returns a JSON-parsable string for every shipped shim', () => {
    for (const name of listShims() as string[]) {
      const p = payloadForHook(name) as string;
      expect(() => JSON.parse(p)).not.toThrow();
      const parsed = JSON.parse(p) as Record<string, unknown>;
      // Every Claude Code event has a `tool_name` and `hook_event_name`.
      expect(parsed).toHaveProperty('tool_name');
      expect(parsed).toHaveProperty('hook_event_name');
    }
  });

  // 0.46.0 charter item 3 — per-hook MATCH + NO_MATCH variants.
  // Every shipped shim must have BOTH variants defined; both must be
  // valid Claude Code event JSON. Shims without a `shim_is_relevant`
  // pre-gate set match === no_match so the profiler can flag them as
  // `same_as_match: true` rather than running redundant measurements.
  describe('0.46.0 charter item 3 — payloadVariantsForHook', () => {
    it('returns { match, no_match } for every shipped shim, both JSON-parsable', () => {
      for (const name of listShims() as string[]) {
        const variants = payloadVariantsForHook(name) as { match: string; no_match: string };
        expect(variants).toHaveProperty('match');
        expect(variants).toHaveProperty('no_match');
        expect(typeof variants.match).toBe('string');
        expect(typeof variants.no_match).toBe('string');
        expect(() => JSON.parse(variants.match)).not.toThrow();
        expect(() => JSON.parse(variants.no_match)).not.toThrow();
        for (const v of [variants.match, variants.no_match]) {
          const parsed = JSON.parse(v) as Record<string, unknown>;
          expect(parsed).toHaveProperty('tool_name');
          expect(parsed).toHaveProperty('hook_event_name');
        }
      }
    });

    it('payloadForHook stays backwards-compatible with the MATCH variant', () => {
      for (const name of listShims() as string[]) {
        const variants = payloadVariantsForHook(name) as { match: string; no_match: string };
        expect(payloadForHook(name)).toBe(variants.match);
      }
    });

    // 0.46.0 charter item 3 — distinct payloads for shims with a
    // `shim_is_relevant` pre-gate. Pre-fix, the harness reused the
    // generic Bash/Write payloads and these shims silently measured
    // the short-circuit path instead of the hot path. This test pins
    // that the new mapping uses DIFFERENT payloads for the shims
    // documented in the charter.
    const SHIMS_WITH_RELEVANCE_GATE = [
      'attribution-advisory.sh',
      'changeset-security-gate.sh',
      'dependency-audit-gate.sh',
      'env-file-protection.sh',
      'secret-scanner.sh',
      'security-disclosure-gate.sh',
    ];

    for (const name of SHIMS_WITH_RELEVANCE_GATE) {
      it(`${name} has distinct MATCH and NO_MATCH variants`, () => {
        const variants = payloadVariantsForHook(name) as { match: string; no_match: string };
        expect(variants.match).not.toBe(variants.no_match);
      });
    }
  });
});

describe('0.45.0 charter item 1 — profile-hooks per-shim p95 ceiling', () => {
  // Single test that runs the full sweep. Vitest timeout extended via
  // the explicit timeout argument — the full sweep across 16 shims at
  // 3 iterations + 1 warmup is ~30-60s on a warm system, sometimes
  // longer on CI. We allow up to 5 minutes.
  //
  // Excluded from the default `pnpm test` chain (see vitest.config.ts
  // exclude); run via `pnpm test:perf` or `pnpm perf:hooks`. This
  // file is not part of the wall-clock-sensitive default suite.
  it(
    'every shim exits 0 under its synthetic payload (codex round-1 P2 #2)',
    () => {
      // Tiny sweep is enough to surface a bad payload — any shim that
      // hits an error path will exit non-zero on every iteration.
      // 0.46.0 charter item 3 — check both match and no_match variants.
      const report = runProfile({ iterations: 2, warmup: 1 }) as {
        hooks: Array<{
          name: string;
          error: string | null;
          exit_codes: number[];
          no_match: { error: string | null; exit_codes: number[] } | null;
        }>;
      };
      const errored = report.hooks.filter(
        (h) => h.error !== null || (h.no_match !== null && h.no_match.error !== null),
      );
      if (errored.length > 0) {
        const summary = errored
          .flatMap((h) => {
            const lines: string[] = [];
            if (h.error !== null) lines.push(`  ${h.name} [match]: ${h.error}`);
            if (h.no_match !== null && h.no_match.error !== null) {
              lines.push(`  ${h.name} [no_match]: ${h.no_match.error}`);
            }
            return lines;
          })
          .join('\n');
        throw new Error(`Shims ran error paths during profiling:\n${summary}`);
      }
      expect(errored).toEqual([]);
    },
    300_000,
  );

  it(
    'no shipped shim exceeds its per-shim p95 ceiling',
    () => {
      const report = runProfile({ iterations: 3, warmup: 1 }) as {
        hooks: Array<{
          name: string;
          p95_ms: number;
          max_ms: number;
          median_ms: number;
          no_match: { p95_ms: number } | null;
        }>;
      };
      // 0.46.0 charter item 3 — enforce ceiling on both variants. The
      // no_match short-circuit must also stay under the ceiling; a
      // regression in the pre-gate path itself would slip through if
      // we only checked the match path.
      const overBudget = report.hooks.filter(
        (h) =>
          h.p95_ms > (ceilingForShim(h.name) as number) ||
          (h.no_match !== null && h.no_match.p95_ms > (ceilingForShim(h.name) as number)),
      );
      if (overBudget.length > 0) {
        const summary = overBudget
          .flatMap((h) => {
            const lines: string[] = [];
            const c = ceilingForShim(h.name) as number;
            if (h.p95_ms > c) {
              lines.push(`  ${h.name} [match]: p95=${h.p95_ms}ms (ceiling=${c}ms)`);
            }
            if (h.no_match !== null && h.no_match.p95_ms > c) {
              lines.push(`  ${h.name} [no_match]: p95=${h.no_match.p95_ms}ms (ceiling=${c}ms)`);
            }
            return lines;
          })
          .join('\n');
        throw new Error(
          `Shims exceeded p95 ceiling:\n${summary}\n` +
            `If this is a measured regression, fix the hot path. ` +
            `If the ceiling is too tight for noisy environments, ` +
            `raise it in scripts/profile-hooks.mjs and document in ` +
            `docs/hook-perf-baseline.md.`,
        );
      }
      expect(overBudget).toEqual([]);
    },
    300_000,
  );
});

describe('0.45.0 charter item 1 — runProfile output shape', () => {
  it(
    'returns hooks sorted by p95 descending',
    () => {
      // Tiny run — 2 iterations, 1 warmup, just to assert sort
      // stability. Vitest needs ~30-60s for this.
      const report = runProfile({ iterations: 2, warmup: 1 }) as {
        version: string;
        platform: string;
        node_version: string;
        iterations: number;
        warmup: number;
        hooks: Array<{ name: string; p95_ms: number }>;
      };
      expect(report.iterations).toBe(2);
      expect(report.warmup).toBe(1);
      expect(report.hooks.length).toBeGreaterThan(0);
      for (let i = 1; i < report.hooks.length; i += 1) {
        expect(report.hooks[i - 1].p95_ms).toBeGreaterThanOrEqual(report.hooks[i].p95_ms);
      }
    },
    300_000,
  );
});
